spring.application.name=incident_classification


#database configuration
spring.datasource.url=jdbc:postgresql://ep-cool-surf-a13o89wv-pooler.ap-southeast-1.aws.neon.tech/incident_db?sslmode=require&channelBinding=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update


# Max file size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Enable file uploads
spring.servlet.multipart.enabled=true




